### PR TITLE
fix(models): enforce string type for default value when 'NULL'

### PR DESCRIPTION
**Pull request by guillaumedeslandes**
Some "NULL" where included in models without quoting due to non-string type for database fields.

eg: DB column type `numeric(12,2)` and default value `NULL::numeric`.

Linked to: CU-78nvya

## Pull Request checklist:

- [ ] Write an explicit title for the Pull Request, following [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/#summary)
- [ ] Create automatic tests
- [ ] No automatic tests failures
- [ ] Test manually the implemented changes
- [ ] Review my own code (indentation, syntax, style, simplicity, readability)
- [ ] Wonder if you can improve the existing code

### CODE REVIEW

**Comment by arnaudbesnier** [comment]
Task linked: [CU-78nvya P1 - Lumber Analyzer generates models where fields have a defaultValue equal to NULL - not accepted by Sequelize.Model](https://app.clickup.com/t/78nvya)

**Comment by slimee** [comment]
It works as expected I guess:
Screenshot 2020-09-16 at 16 58 27

**Comment by slimee** [comment]
You can edit
When you create a record without specifying a value for a numeric/default null field, it display `NaN` 
Screenshot 2020-09-16 at 17 00 51

**Review by slimee — APPROVED** [review]
🚀 it seems good to me.

Maybe another PR is needed for the `NaN` management?

**Pull request merged**
