### PR TITLE
feat(security): use env variables in docker-compose.yml

### PR DESCRIPTION
**Pull request by rap2hpoutre**
It seems it works. **Not tested on Linux though**. See: https://github.com/ForestAdmin/lumber/issues/439

## Pull Request checklist:

- [x] Write an explicit title for the Pull Request, following [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/#summary)
- [ ] Create automatic tests
- [x] No automatic tests failures
- [x] Test manually the implemented changes
- [x] Review my own code (indentation, syntax, style, simplicity, readability)
- [x] Wonder if you can improve the existing code

### CODE REVIEW

**Comment by guillaumedeslandes** [comment]
First comment before testing: shouldn't both `APPLICATION_PORT` and `DATABASE_SSL` be also read from the environment? To ease update for the user.

`NODE_TLS_REJECT_UNAUTHORIZED` and `FOREST_URL` are supposed to never change right?

Do not know if `APPLICATION_PORT` can used in the `ports:` section, but it would seem logical to me, for the "external" port at least.

**Comment by rap2hpoutre** [comment]
You are right: `docker-compose` should not contain generated values anymore: it should entirely rely on `.env` file so users understand where to update their conf.  Let me update this PR!

**Comment by rap2hpoutre** [comment]
Not sure why I can't make `docker-compose up` properly work on a fresh install on my computer (master or this branch) still it seems the env variable replacement works. Could you try to test it @guillaumedeslandes ?

**Comment by guillaumedeslandes** [comment]
In `Dockerfile.hbs` there is a `EXPOSE {{ port }}`. I thing it should take its value at runtime like others in `docker-compose.hbs` via environment variables.

**Review by guillaumedeslandes — APPROVED** [review]

**Pull request merged**
