### PR TITLE
fix(command generate): fix generation of project with postgres on node 14.4

### PR DESCRIPTION
**Pull request by VincentMolinie**
## Pull Request checklist:

- [ ] Write an explicit title for the Pull Request, following [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/#summary)
- [ ] Create automatic tests
- [ ] No automatic tests failures
- [ ] Test manually the implemented changes
- [ ] Review my own code (indentation, syntax, style, simplicity, readability)
- [ ] Wonder if you can improve the existing code

### CODE REVIEW

**Comment by VincentMolinie** [comment]
Task linked: [CU-66r9p7 P2 - Impossible to connect to postgresql database using NodeJS v14.4](https://app.clickup.com/t/66r9p7)

**Comment by SteveBunlon** [comment]
Screenshot 2020-07-01 at 18 19 16

This is what I've got using node version 14.5.0. We must have another issue elsewhere. 

Can you confirm an install work on your machine using node > 14 ?

**Comment by VincentMolinie** [comment]
> st have another

I tried with node 14.4 and it is working fine 🤔. Let me try with 14.5

**Comment by VincentMolinie** [comment]
It worked fine on mongodb (The warning was about mongo), it was it seems just a warning. I upgraded mongo and the warning disappeared 😉

**Comment by SteveBunlon** [comment]
It has nothing to do with mongodb. I tested it again and it works, I must have missed my first test. 

You can remove the Mongodb fix if you wanna strictly stick to the PR name

**Pull request merged**
