### PR TITLE
table-analyzer: add support for FLOAT types

### PR DESCRIPTION
**Pull request by bardiel**
I came across with #52, but still float types were not taken into account.
I've made this very quick and haven't read through all the code, nor test, etc.

Let me know if I should add something else, like changelog or anything.

### CODE REVIEW

**Comment by bardiel** [comment]
@arnaudbesnier @SeyZ Sry, may I bump?

**Comment by bardiel** [comment]
So...

**Comment by arnaudbesnier** [comment]
Let me merge this and add the change description in the changelog

**Comment by bardiel** [comment]
Hahah. Osom! Glad I could help. =P

I have to confess, since I've open the PR (after using my fork to create the models), I left server running and is actively beeing used. Just now I've been asked to make a few changes and remembered about this.

Not kidding, this is the server's uptime:
> 14:25:13 up 339 days, 21:44, ...

**Pull request merged**
